/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clases.GUI;

import java.awt.BorderLayout;
import java.awt.Color;

/**
 *
 * @author Axum
 */
public class Usuario extends javax.swing.JFrame {

    /**
     * Creates new form Usuario
     */
    public Usuario() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        barraSuperior = new javax.swing.JPanel();
        btnPerfil = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        panelSeccionBusqueda = new javax.swing.JPanel();
        btnMenuBusqueda = new javax.swing.JPanel();
        lblBuscar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelContenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(1280, 720));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barraSuperior.setBackground(new java.awt.Color(255, 150, 20));
        barraSuperior.setPreferredSize(new java.awt.Dimension(1280, 70));

        btnPerfil.setPreferredSize(new java.awt.Dimension(200, 50));

        javax.swing.GroupLayout btnPerfilLayout = new javax.swing.GroupLayout(btnPerfil);
        btnPerfil.setLayout(btnPerfilLayout);
        btnPerfilLayout.setHorizontalGroup(
            btnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        btnPerfilLayout.setVerticalGroup(
            btnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        lblTitulo.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lblTitulo.setText("Sistema de Gestion de Biblioteca (SGB)");

        javax.swing.GroupLayout barraSuperiorLayout = new javax.swing.GroupLayout(barraSuperior);
        barraSuperior.setLayout(barraSuperiorLayout);
        barraSuperiorLayout.setHorizontalGroup(
            barraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraSuperiorLayout.createSequentialGroup()
                .addGap(0, 384, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(256, 256, 256)
                .addComponent(btnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        barraSuperiorLayout.setVerticalGroup(
            barraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraSuperiorLayout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addGroup(barraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addComponent(btnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        bg.add(barraSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        panelSeccionBusqueda.setBackground(new java.awt.Color(150, 175, 255));
        panelSeccionBusqueda.setPreferredSize(new java.awt.Dimension(1020, 200));

        btnMenuBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        btnMenuBusqueda.setPreferredSize(new java.awt.Dimension(100, 35));
        btnMenuBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuBusquedaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenuBusquedaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenuBusquedaMouseExited(evt);
            }
        });

        lblBuscar.setText("Menu de Busqueda");

        javax.swing.GroupLayout btnMenuBusquedaLayout = new javax.swing.GroupLayout(btnMenuBusqueda);
        btnMenuBusqueda.setLayout(btnMenuBusquedaLayout);
        btnMenuBusquedaLayout.setHorizontalGroup(
            btnMenuBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnMenuBusquedaLayout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addComponent(lblBuscar)
                .addGap(120, 120, 120))
        );
        btnMenuBusquedaLayout.setVerticalGroup(
            btnMenuBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMenuBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBuscar)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout panelSeccionBusquedaLayout = new javax.swing.GroupLayout(panelSeccionBusqueda);
        panelSeccionBusqueda.setLayout(panelSeccionBusquedaLayout);
        panelSeccionBusquedaLayout.setHorizontalGroup(
            panelSeccionBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSeccionBusquedaLayout.createSequentialGroup()
                .addComponent(btnMenuBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(233, 233, 233)
                .addComponent(jLabel1)
                .addGap(0, 382, Short.MAX_VALUE))
        );
        panelSeccionBusquedaLayout.setVerticalGroup(
            panelSeccionBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSeccionBusquedaLayout.createSequentialGroup()
                .addGroup(panelSeccionBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(btnMenuBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        bg.add(panelSeccionBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1020, 80));

        panelContenedor.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        panelContenedorLayout.setVerticalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        bg.add(panelContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1280, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuBusquedaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuBusquedaMouseEntered
        btnMenuBusqueda.setBackground(new Color (240,240,240));
    }//GEN-LAST:event_btnMenuBusquedaMouseEntered

    private void btnMenuBusquedaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuBusquedaMouseExited
        btnMenuBusqueda.setBackground(new Color (255,255,255));
    }//GEN-LAST:event_btnMenuBusquedaMouseExited

    private void btnMenuBusquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuBusquedaMouseClicked
        
        jLabel1.setText("pulsado");
        PanelBusqueda pb = new PanelBusqueda();
        pb.setSize(1000,440);
        pb.setLocation(0,0);
        panelContenedor.removeAll();
        panelContenedor.add(pb);//BorderLayout.CENTER
        panelContenedor.revalidate();
        panelContenedor.repaint();
        
    }//GEN-LAST:event_btnMenuBusquedaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraSuperior;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btnMenuBusqueda;
    private javax.swing.JPanel btnPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelContenedor;
    private javax.swing.JPanel panelSeccionBusqueda;
    // End of variables declaration//GEN-END:variables
}
