/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import clases.V1.*;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;
import javax.swing.SwingUtilities;


public class panUser extends javax.swing.JPanel {

    
    private DefaultTableModel tblModel;
    private String[] header = {"Libro","Autor","Cantidad","Editorial","Categoria"};
    panPrestamo panP = new panPrestamo();
    
    
    
    public panUser() {
        initComponents();
        initTable();
        btnAjustes.setVisible(false);
        btnLibrosPrestados.setVisible(false);                    
        btnTuPerfil.setVisible(false);
                
        panP.setSize(panP.getPreferredSize());
        
       
                
        bg.add(panP, new org.netbeans.lib.awtextra.AbsoluteConstraints(400,0));
        
        
        panP.setVisible(false);
        
        
        btnEditarPerfil.setVisible(false);
        btnCerrarSesion.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        panTable = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblInventario = new javax.swing.JTable();
        btnSolicitar = new javax.swing.JPanel();
        lblSolicitud = new javax.swing.JLabel();
        lblInfR = new javax.swing.JLabel();
        btnCancelarReservacion = new javax.swing.JPanel();
        lblCancel = new javax.swing.JLabel();
        panSearch = new javax.swing.JPanel();
        txtBusqueda = new javax.swing.JTextField();
        cmbFiltro = new javax.swing.JComboBox<>();
        btnLimpiar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblInfB = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panOptions = new javax.swing.JPanel();
        btnBusqueda = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnPerfil = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnTuPerfil = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnAjustes = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnLibrosPrestados = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnEditarPerfil = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setMinimumSize(new java.awt.Dimension(1280, 640));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panTable.setPreferredSize(new java.awt.Dimension(890, 440));

        tblInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInventarioMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblInventario);

        btnSolicitar.setBackground(new java.awt.Color(255, 153, 153));
        btnSolicitar.setPreferredSize(new java.awt.Dimension(220, 40));
        btnSolicitar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSolicitarMouseClicked(evt);
            }
        });

        lblSolicitud.setText("Solicitar");

        javax.swing.GroupLayout btnSolicitarLayout = new javax.swing.GroupLayout(btnSolicitar);
        btnSolicitar.setLayout(btnSolicitarLayout);
        btnSolicitarLayout.setHorizontalGroup(
            btnSolicitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSolicitarLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(lblSolicitud)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        btnSolicitarLayout.setVerticalGroup(
            btnSolicitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSolicitarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSolicitud)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        lblInfR.setText(".");

        btnCancelarReservacion.setBackground(new java.awt.Color(255, 153, 153));
        btnCancelarReservacion.setPreferredSize(new java.awt.Dimension(220, 40));
        btnCancelarReservacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarReservacionMouseClicked(evt);
            }
        });

        lblCancel.setText("Cancelar Reservacion");

        javax.swing.GroupLayout btnCancelarReservacionLayout = new javax.swing.GroupLayout(btnCancelarReservacion);
        btnCancelarReservacion.setLayout(btnCancelarReservacionLayout);
        btnCancelarReservacionLayout.setHorizontalGroup(
            btnCancelarReservacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCancelarReservacionLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblCancel)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        btnCancelarReservacionLayout.setVerticalGroup(
            btnCancelarReservacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCancelarReservacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCancel)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panTableLayout = new javax.swing.GroupLayout(panTable);
        panTable.setLayout(panTableLayout);
        panTableLayout.setHorizontalGroup(
            panTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panTableLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelarReservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSolicitar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInfR, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(231, 231, 231))
        );
        panTableLayout.setVerticalGroup(
            panTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTableLayout.createSequentialGroup()
                .addGroup(panTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panTableLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(btnSolicitar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelarReservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(lblInfR, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panTableLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        bg.add(panTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 890, 440));

        panSearch.setBackground(new java.awt.Color(245, 255, 255));

        txtBusqueda.setMinimumSize(new java.awt.Dimension(400, 30));
        txtBusqueda.setPreferredSize(new java.awt.Dimension(400, 40));

        cmbFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre del libro", "Autor", "Editorial", "Categoria", "Mostrar todos" }));
        cmbFiltro.setMinimumSize(new java.awt.Dimension(120, 40));
        cmbFiltro.setPreferredSize(new java.awt.Dimension(120, 30));

        btnLimpiar.setBackground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setPreferredSize(new java.awt.Dimension(150, 40));
        btnLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseExited(evt);
            }
        });

        jLabel4.setText("Limpiar");

        javax.swing.GroupLayout btnLimpiarLayout = new javax.swing.GroupLayout(btnLimpiar);
        btnLimpiar.setLayout(btnLimpiarLayout);
        btnLimpiarLayout.setHorizontalGroup(
            btnLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLimpiarLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel4)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        btnLimpiarLayout.setVerticalGroup(
            btnLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnLimpiarLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar.setPreferredSize(new java.awt.Dimension(150, 40));
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarMouseExited(evt);
            }
        });

        jLabel3.setText("Buscar");

        javax.swing.GroupLayout btnBuscarLayout = new javax.swing.GroupLayout(btnBuscar);
        btnBuscar.setLayout(btnBuscarLayout);
        btnBuscarLayout.setHorizontalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnBuscarLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(54, 54, 54))
        );
        btnBuscarLayout.setVerticalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnBuscarLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        lblInfB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfB.setText(".");

        jLabel1.setText("Escriba lo que desea buscar");

        jLabel2.setText("Seleccione tipo de busqueda");

        javax.swing.GroupLayout panSearchLayout = new javax.swing.GroupLayout(panSearch);
        panSearch.setLayout(panSearchLayout);
        panSearchLayout.setHorizontalGroup(
            panSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSearchLayout.createSequentialGroup()
                .addGroup(panSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panSearchLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1)
                            .addGap(211, 211, 211)
                            .addComponent(jLabel2))
                        .addGroup(panSearchLayout.createSequentialGroup()
                            .addGroup(panSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panSearchLayout.createSequentialGroup()
                                    .addGap(146, 146, 146)
                                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(27, 27, 27)
                                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panSearchLayout.createSequentialGroup()
                                    .addGap(103, 103, 103)
                                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(58, 58, 58)
                            .addComponent(cmbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panSearchLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(lblInfB, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        panSearchLayout.setVerticalGroup(
            panSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSearchLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfB)
                .addGap(22, 22, 22)
                .addGroup(panSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        bg.add(panSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 890, 200));

        panOptions.setBackground(new java.awt.Color(47, 91, 252));
        panOptions.setMinimumSize(new java.awt.Dimension(390, 640));
        panOptions.setPreferredSize(new java.awt.Dimension(390, 640));
        panOptions.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBusqueda.setPreferredSize(new java.awt.Dimension(195, 50));
        btnBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBusquedaMouseClicked(evt);
            }
        });

        jLabel6.setText("Buscar");

        javax.swing.GroupLayout btnBusquedaLayout = new javax.swing.GroupLayout(btnBusqueda);
        btnBusqueda.setLayout(btnBusquedaLayout);
        btnBusquedaLayout.setHorizontalGroup(
            btnBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBusquedaLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel6)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        btnBusquedaLayout.setVerticalGroup(
            btnBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBusquedaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel6)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        panOptions.add(btnBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 0, -1, -1));

        btnPerfil.setPreferredSize(new java.awt.Dimension(195, 50));
        btnPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPerfilMouseClicked(evt);
            }
        });

        jLabel5.setText("Perfil");

        javax.swing.GroupLayout btnPerfilLayout = new javax.swing.GroupLayout(btnPerfil);
        btnPerfil.setLayout(btnPerfilLayout);
        btnPerfilLayout.setHorizontalGroup(
            btnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPerfilLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel5)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        btnPerfilLayout.setVerticalGroup(
            btnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPerfilLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel5)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        panOptions.add(btnPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnTuPerfil.setPreferredSize(new java.awt.Dimension(190, 50));
        btnTuPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTuPerfilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTuPerfilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTuPerfilMouseExited(evt);
            }
        });

        jLabel7.setText("Tu Perfil");

        javax.swing.GroupLayout btnTuPerfilLayout = new javax.swing.GroupLayout(btnTuPerfil);
        btnTuPerfil.setLayout(btnTuPerfilLayout);
        btnTuPerfilLayout.setHorizontalGroup(
            btnTuPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTuPerfilLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel7)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        btnTuPerfilLayout.setVerticalGroup(
            btnTuPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTuPerfilLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel7)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        panOptions.add(btnTuPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 190, -1));

        btnAjustes.setPreferredSize(new java.awt.Dimension(190, 50));
        btnAjustes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAjustesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAjustesMouseExited(evt);
            }
        });

        jLabel8.setText("Ajustes");

        javax.swing.GroupLayout btnAjustesLayout = new javax.swing.GroupLayout(btnAjustes);
        btnAjustes.setLayout(btnAjustesLayout);
        btnAjustesLayout.setHorizontalGroup(
            btnAjustesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAjustesLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel8)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        btnAjustesLayout.setVerticalGroup(
            btnAjustesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAjustesLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel8)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        panOptions.add(btnAjustes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        btnLibrosPrestados.setPreferredSize(new java.awt.Dimension(190, 50));
        btnLibrosPrestados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLibrosPrestadosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLibrosPrestadosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLibrosPrestadosMouseExited(evt);
            }
        });

        jLabel9.setText("Prestamos");

        javax.swing.GroupLayout btnLibrosPrestadosLayout = new javax.swing.GroupLayout(btnLibrosPrestados);
        btnLibrosPrestados.setLayout(btnLibrosPrestadosLayout);
        btnLibrosPrestadosLayout.setHorizontalGroup(
            btnLibrosPrestadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLibrosPrestadosLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel9)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        btnLibrosPrestadosLayout.setVerticalGroup(
            btnLibrosPrestadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLibrosPrestadosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel9)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        panOptions.add(btnLibrosPrestados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        btnEditarPerfil.setPreferredSize(new java.awt.Dimension(190, 50));
        btnEditarPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarPerfilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarPerfilMouseExited(evt);
            }
        });

        jLabel11.setText("Editar Perfil");

        javax.swing.GroupLayout btnEditarPerfilLayout = new javax.swing.GroupLayout(btnEditarPerfil);
        btnEditarPerfil.setLayout(btnEditarPerfilLayout);
        btnEditarPerfilLayout.setHorizontalGroup(
            btnEditarPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEditarPerfilLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel11)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        btnEditarPerfilLayout.setVerticalGroup(
            btnEditarPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEditarPerfilLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(14, 14, 14))
        );

        panOptions.add(btnEditarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 200, -1));

        btnCerrarSesion.setPreferredSize(new java.awt.Dimension(190, 50));
        btnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseExited(evt);
            }
        });

        jLabel12.setText("Cerrar Sesion");

        javax.swing.GroupLayout btnCerrarSesionLayout = new javax.swing.GroupLayout(btnCerrarSesion);
        btnCerrarSesion.setLayout(btnCerrarSesionLayout);
        btnCerrarSesionLayout.setHorizontalGroup(
            btnCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCerrarSesionLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel12)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        btnCerrarSesionLayout.setVerticalGroup(
            btnCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCerrarSesionLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(14, 14, 14))
        );

        panOptions.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 200, -1));

        bg.add(panOptions, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 640));

        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseClicked

        limpiarTabla();
    }//GEN-LAST:event_btnLimpiarMouseClicked

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        // TODO add your handling code here:
        if(cmbFiltro.getSelectedIndex() == 0){ //buscar por nombre

            limpiarTabla();

            String nombre = txtBusqueda.getText();
            txtBusqueda.setText("");

            Libro l = Exe.almacen.mostrarPorNombre(nombre);
            if(l == null){
                lblInfB.setText("No se encuentra el libro");
            }
            else{
                tblModel.addRow(l.toArray());
            }

        }
        if(cmbFiltro.getSelectedIndex() == 1){ // buscar por autor
            limpiarTabla();

            String nombre = txtBusqueda.getText();
            txtBusqueda.setText("");

            Exe.listaSalida = Exe.almacen.mostrarPorAutor(nombre);

            for(int i = 0; i < Exe.listaSalida.size(); i++){
                Libro l = Exe.listaSalida.get(i);
                tblModel.addRow(l.toArray());
            }
            Exe.listaSalida.clear();
        }

        if(cmbFiltro.getSelectedIndex() == 2){

            limpiarTabla();

            String nombre = txtBusqueda.getText();
            txtBusqueda.setText("");

            Exe.listaSalida = Exe.almacen.mostrarPorEditorial(nombre);

            for(int i = 0; i < Exe.listaSalida.size(); i++){
                Libro l = Exe.listaSalida.get(i);
                tblModel.addRow(l.toArray());
            }
            Exe.listaSalida.clear();
        }

        if(cmbFiltro.getSelectedIndex() == 3){
            limpiarTabla();

            String nombre = txtBusqueda.getText();
            txtBusqueda.setText("");

            Exe.listaSalida = Exe.almacen.mostrarPorCategoria(nombre);

            for(int i = 0; i < Exe.listaSalida.size(); i++){
                Libro l = Exe.listaSalida.get(i);
                tblModel.addRow(l.toArray());
            }
            Exe.listaSalida.clear();
        }

        if(cmbFiltro.getSelectedIndex() == 4){
            limpiarTabla();

            Exe.listaSalida = Exe.almacen.mostrarTodos();

            for(int i = 0; i < Exe.listaSalida.size(); i++){
                Libro l = Exe.listaSalida.get(i);
                tblModel.addRow(l.toArray());
            }
        }
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void btnSolicitarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSolicitarMouseClicked
        // TODO add your handling code here:
        
        if(tblInventario.getSelectedRowCount() != 1){
            return;
        }
        int fila = tblInventario.getSelectedRow();        
        String nombreSolicitud = (String) tblModel.getValueAt(fila,0);  
        int cantidad = (int) tblModel.getValueAt(fila,2); 
        boolean existencia = true;
        Libro l = Exe.almacen.mostrarPorNombre(nombreSolicitud); 
        
        if(cantidad > 0 && true){             
            //yo se que es redundante mostrar dos veces el arbol, podria simplemente editar la tabla y luego el arbol pero es por seguir la filosofia de primero arbol, luego mostrar datos al editar
           
            lblSolicitud.setText("Solicitar");  
            existencia = Exe.cliente.añadirLibro(l);
            
            if(existencia == false){
                //ya esta el libro solicitado
                lblInfR.setText("Ya solicito el libro.");
                
            }
            else{
                Exe.almacen.retirarUnidad(nombreSolicitud);
                lblInfR.setText("Ha solicitado el libro exitosamente.");
                Libro l2 = Exe.almacen.mostrarPorNombre(nombreSolicitud);            
                tblInventario.setValueAt(l2.getCantidad(),fila,2);
            } 
        }
        if(cantidad == 0 && Exe.cliente.buscarLibro(l) != l ){ //totalmente funcional, ya si el libro lo pidio, no lo puede reservar
            
            lblSolicitud.setText("Reservar");
            
            
            int condReservar = Exe.almacen.reservarLibro(Exe.cliente.getNombre(), nombreSolicitud); 
            switch(condReservar) {
                case 0:
                    lblInfR.setText("El libro buscado no existe.");
                    break;
                case 1:
                    lblInfR.setText("Ya tiene reservado el libro. Espere a que este disponible.");
                    break;
                case 2:
                    lblInfR.setText("Ha sido añadido a la cola de espera.");     
                    break;
            }
        }
        
        

        //tblModel.removeRow(fila);
    }//GEN-LAST:event_btnSolicitarMouseClicked

    private void btnCancelarReservacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarReservacionMouseClicked
        if(tblInventario.getSelectedRowCount() != 1){
            return;
        }
        int fila = tblInventario.getSelectedRow();        
        String nombreCancelacion = (String) tblModel.getValueAt(fila,0);  
        Exe.almacen.cancelarReserva(Exe.cliente.getNombre(), nombreCancelacion);
        
    }//GEN-LAST:event_btnCancelarReservacionMouseClicked

    private void tblInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInventarioMouseClicked
        if(evt.getClickCount() == 1 || evt.getClickCount() == 2 ){
            int fila = tblInventario.getSelectedRow();             
            int cantidad = (int) tblModel.getValueAt(fila,2); 
            if(cantidad > 0){
                btnSolicitar.setBackground(Color.BLUE);
                lblSolicitud.setText("Solicitar");
                btnCancelarReservacion.setVisible(false);
            }
            if(cantidad == 0){
                btnSolicitar.setBackground(Color.RED);                
                lblSolicitud.setText("Reservar");
                btnCancelarReservacion.setVisible(true);
                
            }
            else{
                
            }
        }   
    }//GEN-LAST:event_tblInventarioMouseClicked

    private void btnPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerfilMouseClicked
        panTable.setVisible(false);
        panSearch.setVisible(false);
        
        btnAjustes.setVisible(true);
        btnLibrosPrestados.setVisible(true);                   
        btnTuPerfil.setVisible(true);
        
        panP.setVisible(false);
       
        
        btnEditarPerfil.setVisible(false);
        btnCerrarSesion.setVisible(false);
        
    }//GEN-LAST:event_btnPerfilMouseClicked

    private void btnBusquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBusquedaMouseClicked
        panTable.setVisible(true);
        panSearch.setVisible(true); 
        
        btnAjustes.setVisible(false);
        btnLibrosPrestados.setVisible(false);                   
        btnTuPerfil.setVisible(false);
        
        panP.setVisible(false);
        
        
        btnEditarPerfil.setVisible(false);
        btnCerrarSesion.setVisible(false);
    }//GEN-LAST:event_btnBusquedaMouseClicked

    private void btnLibrosPrestadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLibrosPrestadosMouseClicked
        panP.setVisible(true);
        
        
        btnEditarPerfil.setVisible(false);
        btnCerrarSesion.setVisible(false);
        

    }//GEN-LAST:event_btnLibrosPrestadosMouseClicked

    private void btnLimpiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseEntered
        // TODO add your handling code here:
        btnLimpiar.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnLimpiarMouseEntered

    private void btnLimpiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseExited
        // TODO add your handling code here:
        btnLimpiar.setBackground(new Color(242,242,242));
    }//GEN-LAST:event_btnLimpiarMouseExited

    private void btnBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseEntered
        // TODO add your handling code here:
        btnBuscar.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnBuscarMouseEntered

    private void btnBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseExited
        // TODO add your handling code here:
        btnBuscar.setBackground(new Color(242,242,242));
    }//GEN-LAST:event_btnBuscarMouseExited

    private void btnLibrosPrestadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLibrosPrestadosMouseEntered
        // TODO add your handling code here:
        btnLibrosPrestados.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnLibrosPrestadosMouseEntered

    private void btnLibrosPrestadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLibrosPrestadosMouseExited
        // TODO add your handling code here:
        btnLibrosPrestados.setBackground(new Color(242,242,242));
    }//GEN-LAST:event_btnLibrosPrestadosMouseExited

    private void btnAjustesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjustesMouseEntered
        // TODO add your handling code here:
        btnAjustes.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnAjustesMouseEntered

    private void btnAjustesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjustesMouseExited
        // TODO add your handling code here:
        btnAjustes.setBackground(new Color(242,242,242));
    }//GEN-LAST:event_btnAjustesMouseExited

    private void btnTuPerfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTuPerfilMouseEntered
        // TODO add your handling code here:
        btnTuPerfil.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnTuPerfilMouseEntered

    private void btnTuPerfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTuPerfilMouseExited
        // TODO add your handling code here:
        btnTuPerfil.setBackground(new Color(242,242,242));
    }//GEN-LAST:event_btnTuPerfilMouseExited

    private void btnTuPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTuPerfilMouseClicked
        // TODO add your handling code here:
        btnEditarPerfil.setVisible(true);
        btnCerrarSesion.setVisible(true);
        
        
    }//GEN-LAST:event_btnTuPerfilMouseClicked

    private void btnCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseClicked
        // TODO add your handling code here:
        
        Exe frame = (Exe) SwingUtilities.getWindowAncestor(panUser.this);
        frame.selInit(1);
    }//GEN-LAST:event_btnCerrarSesionMouseClicked

    private void btnEditarPerfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarPerfilMouseEntered
        // TODO add your handling code here:
        btnEditarPerfil.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnEditarPerfilMouseEntered

    private void btnCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseEntered
        // TODO add your handling code here:
        btnCerrarSesion.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnCerrarSesionMouseEntered

    private void btnEditarPerfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarPerfilMouseExited
        // TODO add your handling code here:
        btnEditarPerfil.setBackground(new Color(242,242,242));
    }//GEN-LAST:event_btnEditarPerfilMouseExited

    private void btnCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseExited
        // TODO add your handling code here:
        btnCerrarSesion.setBackground(new Color(242,242,242));
    }//GEN-LAST:event_btnCerrarSesionMouseExited
    
    private void limpiarTabla(){
        for(int i = 0; i < tblInventario.getRowCount(); i++ ){
            tblModel.removeRow(i);
            i --;
        }
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btnAjustes;
    private javax.swing.JPanel btnBuscar;
    private javax.swing.JPanel btnBusqueda;
    private javax.swing.JPanel btnCancelarReservacion;
    private javax.swing.JPanel btnCerrarSesion;
    private javax.swing.JPanel btnEditarPerfil;
    private javax.swing.JPanel btnLibrosPrestados;
    private javax.swing.JPanel btnLimpiar;
    private javax.swing.JPanel btnPerfil;
    private javax.swing.JPanel btnSolicitar;
    private javax.swing.JPanel btnTuPerfil;
    private javax.swing.JComboBox<String> cmbFiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCancel;
    private javax.swing.JLabel lblInfB;
    private javax.swing.JLabel lblInfR;
    private javax.swing.JLabel lblSolicitud;
    private javax.swing.JPanel panOptions;
    private javax.swing.JPanel panSearch;
    private javax.swing.JPanel panTable;
    private javax.swing.JTable tblInventario;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables

    private void initTable() {
        tblModel = new DefaultTableModel(header,0){
        @Override
        public boolean isCellEditable(int row, int column){
            return false;
            }
        };
        tblInventario.setModel(tblModel);
        
        
    }
}
