/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import clases.V1.*;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;


public class panUser extends javax.swing.JPanel {

    
    private DefaultTableModel tblModel;
    private String[] header = {"Libro","Autor","Cantidad","Editorial","Categoria"};
    panPrestamo panP = new panPrestamo();
    
    
    
    public panUser() {
        initComponents();
        initTable();
        btnAjustes.setVisible(false);
        btnPrestamos.setVisible(false);                    
        btnTuPerfil.setVisible(false);
                
        panP.setSize(panP.getPreferredSize());
        
       
                
        bg.add(panP, new org.netbeans.lib.awtextra.AbsoluteConstraints(400,0));
        
        
        panP.setVisible(false);
        
        
        btnEditarPerfil.setVisible(false);
        btnCerrarSesion.setVisible(false);
        btnSolicitar.setVisible(false);
        btnCancelarReservacion.setVisible(false);
        
        
        setHeaderFont(tblInventario.getTableHeader(), new Font("Yu Gothic UI", Font.BOLD, 40));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        panTable = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblInventario = new javax.swing.JTable();
        btnSolicitar = new javax.swing.JPanel();
        lblSolicitud = new javax.swing.JLabel();
        lblInfR = new javax.swing.JLabel();
        btnCancelarReservacion = new javax.swing.JPanel();
        lblCancel = new javax.swing.JLabel();
        panSearch = new javax.swing.JPanel();
        txtBusqueda = new javax.swing.JTextField();
        cmbFiltro = new javax.swing.JComboBox<>();
        btnLimpiar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblInfB = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panOptions = new javax.swing.JPanel();
        btnBusqueda = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnPerfil = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnTuPerfil = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnAjustes = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnPrestamos = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnEditarPerfil = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setMinimumSize(new java.awt.Dimension(1280, 640));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panTable.setBackground(new java.awt.Color(248, 248, 248));
        panTable.setPreferredSize(new java.awt.Dimension(890, 440));
        panTable.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblInventario.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        tblInventario.setForeground(new java.awt.Color(30, 89, 29));
        tblInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblInventario.setRowHeight(30);
        tblInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInventarioMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblInventario);

        panTable.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 92, 820, 330));

        btnSolicitar.setBackground(new java.awt.Color(230, 240, 230));
        btnSolicitar.setPreferredSize(new java.awt.Dimension(220, 40));
        btnSolicitar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSolicitarMouseClicked(evt);
            }
        });

        lblSolicitud.setFont(new java.awt.Font("Eras Medium ITC", 0, 15)); // NOI18N
        lblSolicitud.setForeground(new java.awt.Color(22, 67, 36));
        lblSolicitud.setText("Solicitar");

        javax.swing.GroupLayout btnSolicitarLayout = new javax.swing.GroupLayout(btnSolicitar);
        btnSolicitar.setLayout(btnSolicitarLayout);
        btnSolicitarLayout.setHorizontalGroup(
            btnSolicitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSolicitarLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(lblSolicitud)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        btnSolicitarLayout.setVerticalGroup(
            btnSolicitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSolicitarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSolicitud)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        panTable.add(btnSolicitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 181, -1));

        lblInfR.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        lblInfR.setText(".");
        panTable.add(lblInfR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 310, 32));

        btnCancelarReservacion.setBackground(new java.awt.Color(250, 150, 50));
        btnCancelarReservacion.setPreferredSize(new java.awt.Dimension(220, 40));
        btnCancelarReservacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarReservacionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarReservacionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarReservacionMouseExited(evt);
            }
        });

        lblCancel.setFont(new java.awt.Font("Eras Medium ITC", 0, 15)); // NOI18N
        lblCancel.setForeground(new java.awt.Color(22, 67, 36));
        lblCancel.setText("Cancelar Reservacion");

        javax.swing.GroupLayout btnCancelarReservacionLayout = new javax.swing.GroupLayout(btnCancelarReservacion);
        btnCancelarReservacion.setLayout(btnCancelarReservacionLayout);
        btnCancelarReservacionLayout.setHorizontalGroup(
            btnCancelarReservacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCancelarReservacionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCancel)
                .addGap(26, 26, 26))
        );
        btnCancelarReservacionLayout.setVerticalGroup(
            btnCancelarReservacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCancelarReservacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCancel)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        panTable.add(btnCancelarReservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 181, -1));

        bg.add(panTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 890, 440));

        panSearch.setBackground(new java.awt.Color(255, 255, 255));
        panSearch.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBusqueda.setBackground(new java.awt.Color(240, 250, 240));
        txtBusqueda.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtBusqueda.setForeground(new java.awt.Color(153, 153, 153));
        txtBusqueda.setText("Escriba lo que desea buscar");
        txtBusqueda.setMinimumSize(new java.awt.Dimension(400, 30));
        txtBusqueda.setPreferredSize(new java.awt.Dimension(400, 40));
        txtBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBusquedaMouseClicked(evt);
            }
        });
        txtBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaActionPerformed(evt);
            }
        });
        panSearch.add(txtBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 445, 37));

        cmbFiltro.setBackground(new java.awt.Color(240, 250, 240));
        cmbFiltro.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        cmbFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre del libro", "Autor", "Editorial", "Categoria", "Mostrar todos" }));
        cmbFiltro.setMinimumSize(new java.awt.Dimension(120, 40));
        cmbFiltro.setPreferredSize(new java.awt.Dimension(120, 30));
        panSearch.add(cmbFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 181, 37));

        btnLimpiar.setBackground(new java.awt.Color(230, 240, 230));
        btnLimpiar.setPreferredSize(new java.awt.Dimension(150, 40));
        btnLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Eras Medium ITC", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(22, 67, 36));
        jLabel4.setText("Limpiar");

        javax.swing.GroupLayout btnLimpiarLayout = new javax.swing.GroupLayout(btnLimpiar);
        btnLimpiar.setLayout(btnLimpiarLayout);
        btnLimpiarLayout.setHorizontalGroup(
            btnLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnLimpiarLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(51, 51, 51))
        );
        btnLimpiarLayout.setVerticalGroup(
            btnLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLimpiarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        panSearch.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, -1, -1));

        btnBuscar.setBackground(new java.awt.Color(230, 240, 230));
        btnBuscar.setPreferredSize(new java.awt.Dimension(150, 40));
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Eras Medium ITC", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(22, 67, 36));
        jLabel3.setText("Buscar");

        javax.swing.GroupLayout btnBuscarLayout = new javax.swing.GroupLayout(btnBuscar);
        btnBuscar.setLayout(btnBuscarLayout);
        btnBuscarLayout.setHorizontalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBuscarLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel3)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        btnBuscarLayout.setVerticalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        panSearch.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, -1));

        lblInfB.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        lblInfB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfB.setText(".");
        panSearch.add(lblInfB, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 300, -1));

        jLabel2.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel2.setText("Seleccione tipo de busqueda");
        panSearch.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(606, 11, -1, 29));

        bg.add(panSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 890, 200));

        panOptions.setBackground(new java.awt.Color(230, 240, 230));
        panOptions.setMinimumSize(new java.awt.Dimension(390, 640));
        panOptions.setPreferredSize(new java.awt.Dimension(390, 640));
        panOptions.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBusqueda.setBackground(new java.awt.Color(125, 160, 110));
        btnBusqueda.setPreferredSize(new java.awt.Dimension(195, 50));
        btnBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBusquedaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBusquedaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBusquedaMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Eras Medium ITC", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Desplegar menu busqueda");

        javax.swing.GroupLayout btnBusquedaLayout = new javax.swing.GroupLayout(btnBusqueda);
        btnBusqueda.setLayout(btnBusquedaLayout);
        btnBusquedaLayout.setHorizontalGroup(
            btnBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnBusquedaLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );
        btnBusquedaLayout.setVerticalGroup(
            btnBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBusquedaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel6)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        panOptions.add(btnBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 0, -1, -1));

        btnPerfil.setBackground(new java.awt.Color(125, 160, 110));
        btnPerfil.setPreferredSize(new java.awt.Dimension(195, 50));
        btnPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPerfilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPerfilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPerfilMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Eras Medium ITC", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Perfil");

        javax.swing.GroupLayout btnPerfilLayout = new javax.swing.GroupLayout(btnPerfil);
        btnPerfil.setLayout(btnPerfilLayout);
        btnPerfilLayout.setHorizontalGroup(
            btnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPerfilLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel5)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        btnPerfilLayout.setVerticalGroup(
            btnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPerfilLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(14, 14, 14))
        );

        panOptions.add(btnPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnTuPerfil.setBackground(new java.awt.Color(230, 240, 230));
        btnTuPerfil.setPreferredSize(new java.awt.Dimension(190, 50));
        btnTuPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTuPerfilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTuPerfilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTuPerfilMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Eras Medium ITC", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(32, 72, 33));
        jLabel7.setText("Tu Perfil");

        javax.swing.GroupLayout btnTuPerfilLayout = new javax.swing.GroupLayout(btnTuPerfil);
        btnTuPerfil.setLayout(btnTuPerfilLayout);
        btnTuPerfilLayout.setHorizontalGroup(
            btnTuPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTuPerfilLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel7)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        btnTuPerfilLayout.setVerticalGroup(
            btnTuPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTuPerfilLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel7)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        panOptions.add(btnTuPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 190, -1));

        btnAjustes.setBackground(new java.awt.Color(230, 240, 230));
        btnAjustes.setPreferredSize(new java.awt.Dimension(190, 50));
        btnAjustes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAjustesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAjustesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAjustesMouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Eras Medium ITC", 0, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(32, 72, 33));
        jLabel8.setText("Ajustes");

        javax.swing.GroupLayout btnAjustesLayout = new javax.swing.GroupLayout(btnAjustes);
        btnAjustes.setLayout(btnAjustesLayout);
        btnAjustesLayout.setHorizontalGroup(
            btnAjustesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAjustesLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel8)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        btnAjustesLayout.setVerticalGroup(
            btnAjustesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAjustesLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel8)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        panOptions.add(btnAjustes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        btnPrestamos.setBackground(new java.awt.Color(230, 240, 230));
        btnPrestamos.setPreferredSize(new java.awt.Dimension(190, 50));
        btnPrestamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrestamosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPrestamosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPrestamosMouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Eras Medium ITC", 0, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(32, 72, 33));
        jLabel9.setText("Prestamos");

        javax.swing.GroupLayout btnPrestamosLayout = new javax.swing.GroupLayout(btnPrestamos);
        btnPrestamos.setLayout(btnPrestamosLayout);
        btnPrestamosLayout.setHorizontalGroup(
            btnPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPrestamosLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel9)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        btnPrestamosLayout.setVerticalGroup(
            btnPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPrestamosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel9)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        panOptions.add(btnPrestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        btnEditarPerfil.setBackground(new java.awt.Color(230, 240, 230));
        btnEditarPerfil.setPreferredSize(new java.awt.Dimension(190, 50));
        btnEditarPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarPerfilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarPerfilMouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Eras Medium ITC", 0, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(32, 72, 33));
        jLabel11.setText("Editar Perfil");

        javax.swing.GroupLayout btnEditarPerfilLayout = new javax.swing.GroupLayout(btnEditarPerfil);
        btnEditarPerfil.setLayout(btnEditarPerfilLayout);
        btnEditarPerfilLayout.setHorizontalGroup(
            btnEditarPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEditarPerfilLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel11)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        btnEditarPerfilLayout.setVerticalGroup(
            btnEditarPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEditarPerfilLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(14, 14, 14))
        );

        panOptions.add(btnEditarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 200, -1));

        btnCerrarSesion.setBackground(new java.awt.Color(255, 210, 210));
        btnCerrarSesion.setPreferredSize(new java.awt.Dimension(190, 50));
        btnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseExited(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Eras Medium ITC", 0, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(32, 72, 33));
        jLabel12.setText("Cerrar Sesion");

        javax.swing.GroupLayout btnCerrarSesionLayout = new javax.swing.GroupLayout(btnCerrarSesion);
        btnCerrarSesion.setLayout(btnCerrarSesionLayout);
        btnCerrarSesionLayout.setHorizontalGroup(
            btnCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCerrarSesionLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel12)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        btnCerrarSesionLayout.setVerticalGroup(
            btnCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCerrarSesionLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(14, 14, 14))
        );

        panOptions.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 200, -1));

        bg.add(panOptions, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 640));

        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseClicked

        limpiarTabla();
        txtBusqueda.setText("");
        lblInfR.setText(""); 
    }//GEN-LAST:event_btnLimpiarMouseClicked

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        // TODO add your handling code here:
        if(cmbFiltro.getSelectedIndex() == 0){ //buscar por nombre

            limpiarTabla();

            String nombre = txtBusqueda.getText();
            txtBusqueda.setText("");

            Libro l = Exe.almacen.mostrarPorNombre(nombre);
            if(l == null){
                lblInfB.setText("No se encuentra el libro");
            }
            else{
                tblModel.addRow(l.toArray());
            }
            
            if(tblModel.getRowCount() == 0) {
            lblInfB.setText("No se encontro ningun libro.");
            }
        
            else {
            lblInfB.setText("Se encontro el libro.");
            }
        /////////////////////////////////////////////////////////////////////////////////
        }
        if(cmbFiltro.getSelectedIndex() == 1){ // buscar por autor
            limpiarTabla();

            String nombre = txtBusqueda.getText();
            txtBusqueda.setText("");

            Exe.listaSalida = Exe.almacen.mostrarPorAutor(nombre);

            for(int i = 0; i < Exe.listaSalida.size(); i++){
                Libro l = Exe.listaSalida.get(i);
                tblModel.addRow(l.toArray());
            }
            Exe.listaSalida.clear();
        }
        if(tblModel.getRowCount() == 0) {
            lblInfB.setText("No se encontro ningun libro con el autor mencionado");
            }
        
            else {
            lblInfB.setText("Se encontraron los siguientes libros con el autor mencionado");
            }
        //////////////////////////////////////////////////////////////////////////////////
        if(cmbFiltro.getSelectedIndex() == 2){

            limpiarTabla();

            String nombre = txtBusqueda.getText();
            txtBusqueda.setText("");

            Exe.listaSalida = Exe.almacen.mostrarPorEditorial(nombre);

            for(int i = 0; i < Exe.listaSalida.size(); i++){
                Libro l = Exe.listaSalida.get(i);
                tblModel.addRow(l.toArray());
            }
            Exe.listaSalida.clear();
        }
        if(tblModel.getRowCount() == 0) {
            lblInfB.setText("No se encontro ningun libro con la editorial mencionada.");
            }
        
            else {
            lblInfB.setText("Se encontraron los siguientes libros con la editorial mencionada.");
            }
        //////////////////////////////////////////////////////////////////////////////////
        if(cmbFiltro.getSelectedIndex() == 3){
            limpiarTabla();

            String nombre = txtBusqueda.getText();
            txtBusqueda.setText("");

            Exe.listaSalida = Exe.almacen.mostrarPorCategoria(nombre);

            for(int i = 0; i < Exe.listaSalida.size(); i++){
                Libro l = Exe.listaSalida.get(i);
                tblModel.addRow(l.toArray());
            }
            Exe.listaSalida.clear();
        }
        if(tblModel.getRowCount() == 0) {
            lblInfB.setText("No se encontro ningun libro con la categoria propuesta.");
            }
        
            else {
            lblInfB.setText("Se encontraron los siguientes libros con la categoria propuesta.");
            }
        /////////////////////////////////////////////////////////////////////////////////
        if(cmbFiltro.getSelectedIndex() == 4){
            limpiarTabla();

            Exe.listaSalida = Exe.almacen.mostrarTodos();

            for(int i = 0; i < Exe.listaSalida.size(); i++){
                Libro l = Exe.listaSalida.get(i);
                tblModel.addRow(l.toArray());
            }
            if(tblModel.getRowCount() == 0) {
            lblInfB.setText("No se encontro ningun libro en el inventario");
            }
        
            else {
            lblInfB.setText("Se muestran todos los libros de la biblioteca.");
            }
        }
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void btnSolicitarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSolicitarMouseClicked
        // TODO add your handling code here:
        
        if(tblInventario.getSelectedRowCount() != 1){
            return;
        }
        int fila = tblInventario.getSelectedRow();        
        String nombreSolicitud = (String) tblModel.getValueAt(fila,0);  
        int cantidad = (int) tblModel.getValueAt(fila,2); 
        boolean existencia = true;
        Libro l = Exe.almacen.mostrarPorNombre(nombreSolicitud); 
        
        if(cantidad > 0 && true){             
            //yo se que es redundante mostrar dos veces el arbol, podria simplemente editar la tabla y luego el arbol pero es por seguir la filosofia de primero arbol, luego mostrar datos al editar
           
            lblSolicitud.setText("Solicitar");  
            existencia = Exe.cliente.añadirLibro(l);
            
            if(existencia == false){
                //ya esta el libro solicitado
                lblInfR.setText("Ya solicito el libro.");
                
            }
            else{
                Exe.almacen.retirarUnidad(nombreSolicitud);
                lblInfR.setText("Ha solicitado el libro exitosamente.");
                Libro l2 = Exe.almacen.mostrarPorNombre(nombreSolicitud);            
                tblInventario.setValueAt(l2.getCantidad(),fila,2);
            } 
        }
        if(cantidad == 0 && Exe.cliente.buscarLibro(l) != l ){ //totalmente funcional, ya si el libro lo pidio, no lo puede reservar
            
            lblSolicitud.setText("Reservar");
            
            
            int condReservar = Exe.almacen.reservarLibro(Exe.cliente.getNombre(), nombreSolicitud); 
            switch(condReservar) {
                case 0:
                    lblInfR.setText("El libro buscado no existe.");
                    break;
                case 1:
                    lblInfR.setText("Ya tiene reservado el libro.");
                    break;
                case 2:
                    lblInfR.setText("Ha sido añadido a la cola de espera.");     
                    break;
            }
        }
        
        

        //tblModel.removeRow(fila);
    }//GEN-LAST:event_btnSolicitarMouseClicked

    private void btnCancelarReservacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarReservacionMouseClicked
        if(tblInventario.getSelectedRowCount() != 1){
            return;
        }
        int fila = tblInventario.getSelectedRow();        
        String nombreCancelacion = (String) tblModel.getValueAt(fila,0);  
        Exe.almacen.cancelarReserva(Exe.cliente.getNombre(), nombreCancelacion);
        lblInfR.setText("Ha cancelado la reserva del libro"); 
        
    }//GEN-LAST:event_btnCancelarReservacionMouseClicked

    private void tblInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInventarioMouseClicked
        if(evt.getClickCount() == 1 || evt.getClickCount() == 2 ){
            int fila = tblInventario.getSelectedRow();             
            int cantidad = (int) tblModel.getValueAt(fila,2); 
            btnSolicitar.setVisible(true);
            if(cantidad > 0){
                btnSolicitar.setBackground(new Color(210,230,210));
                lblSolicitud.setText("Solicitar");
                btnCancelarReservacion.setVisible(false);
                lblInfR.setText("Puede solicitar el libro");
            }
            if(cantidad == 0){
                btnSolicitar.setBackground(new Color(250,150,50));                
                lblSolicitud.setText("Reservar");
                btnCancelarReservacion.setVisible(true);
                lblInfR.setText("No hay libros disponibles, puede reservar.");
            }
            else{
                //lblInfR.setText("");
            }
        }   
    }//GEN-LAST:event_tblInventarioMouseClicked

    private void btnPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerfilMouseClicked
        //panTable.setVisible(false);
        //panSearch.setVisible(false);
        
        btnAjustes.setVisible(true);
        btnPrestamos.setVisible(true);                   
        btnTuPerfil.setVisible(true);
        
        //panP.setVisible(false);
       
        
        btnEditarPerfil.setVisible(false);
        btnCerrarSesion.setVisible(false);
        
    }//GEN-LAST:event_btnPerfilMouseClicked

    private void btnBusquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBusquedaMouseClicked
        panTable.setVisible(true);
        panSearch.setVisible(true); 
        
        btnAjustes.setVisible(false);
        btnPrestamos.setVisible(false);                   
        btnTuPerfil.setVisible(false);
        
        panP.setVisible(false);
        
        
        btnEditarPerfil.setVisible(false);
        btnCerrarSesion.setVisible(false);
    }//GEN-LAST:event_btnBusquedaMouseClicked

    private void btnPrestamosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrestamosMouseClicked
        
        panTable.setVisible(false);
        panSearch.setVisible(false);
        
        
        panP.setVisible(true);
        
        
        btnEditarPerfil.setVisible(false);
        btnCerrarSesion.setVisible(false);
        

    }//GEN-LAST:event_btnPrestamosMouseClicked

    private void btnLimpiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseEntered
        // TODO add your handling code here:
        btnLimpiar.setBackground(new Color(200,230,200));
    }//GEN-LAST:event_btnLimpiarMouseEntered

    private void btnLimpiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseExited
        // TODO add your handling code here:
        btnLimpiar.setBackground(new Color(230,240,230));
    }//GEN-LAST:event_btnLimpiarMouseExited

    private void btnBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseEntered
        // TODO add your handling code here:
        btnBuscar.setBackground(new Color(200,230,200));
    }//GEN-LAST:event_btnBuscarMouseEntered

    private void btnBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseExited
        // TODO add your handling code here:
        btnBuscar.setBackground(new Color(230,240,230));
    }//GEN-LAST:event_btnBuscarMouseExited

    private void btnPrestamosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrestamosMouseEntered
        // TODO add your handling code here:
        btnPrestamos.setBackground(new Color(200,230,200));
    }//GEN-LAST:event_btnPrestamosMouseEntered

    private void btnPrestamosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrestamosMouseExited
        // TODO add your handling code here:
        btnPrestamos.setBackground(new Color(230,240,230));
    }//GEN-LAST:event_btnPrestamosMouseExited

    private void btnAjustesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjustesMouseEntered
        // TODO add your handling code here:
        btnAjustes.setBackground(new Color(200,230,200));
    }//GEN-LAST:event_btnAjustesMouseEntered

    private void btnAjustesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjustesMouseExited
        // TODO add your handling code here:
        btnAjustes.setBackground(new Color(230,240,230));
    }//GEN-LAST:event_btnAjustesMouseExited

    private void btnTuPerfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTuPerfilMouseEntered
        // TODO add your handling code here:
        btnTuPerfil.setBackground(new Color(200,230,200));
    }//GEN-LAST:event_btnTuPerfilMouseEntered

    private void btnTuPerfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTuPerfilMouseExited
        // TODO add your handling code here:
        btnTuPerfil.setBackground(new Color(230,240,230));
    }//GEN-LAST:event_btnTuPerfilMouseExited

    private void btnTuPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTuPerfilMouseClicked
        // TODO add your handling code here:
        btnEditarPerfil.setVisible(true);
        btnCerrarSesion.setVisible(true);
        
        
        
    }//GEN-LAST:event_btnTuPerfilMouseClicked

    private void btnCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseClicked
        // TODO add your handling code here:
        
        Exe frame = (Exe) SwingUtilities.getWindowAncestor(panUser.this);
        frame.selInit(1);
    }//GEN-LAST:event_btnCerrarSesionMouseClicked

    private void btnEditarPerfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarPerfilMouseEntered
        // TODO add your handling code here:
        btnEditarPerfil.setBackground(new Color(225,240,225));
    }//GEN-LAST:event_btnEditarPerfilMouseEntered

    private void btnCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseEntered
        // TODO add your handling code here:
        btnCerrarSesion.setBackground(new Color(255,225,225));
    }//GEN-LAST:event_btnCerrarSesionMouseEntered

    private void btnEditarPerfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarPerfilMouseExited
        // TODO add your handling code here:
        btnEditarPerfil.setBackground(new Color(210,230,210));
    }//GEN-LAST:event_btnEditarPerfilMouseExited

    private void btnCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseExited
        // TODO add your handling code here:
        btnCerrarSesion.setBackground(new Color(255,210,210));
    }//GEN-LAST:event_btnCerrarSesionMouseExited

    private void btnPerfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerfilMouseEntered
        btnPerfil.setBackground(new Color(195,220,180));
    }//GEN-LAST:event_btnPerfilMouseEntered

    private void btnPerfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerfilMouseExited
        btnPerfil.setBackground(new Color(125,160,110));
    }//GEN-LAST:event_btnPerfilMouseExited
        
    private void btnBusquedaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBusquedaMouseEntered
        btnBusqueda.setBackground(new Color(195,220,180));
    }//GEN-LAST:event_btnBusquedaMouseEntered

    private void btnBusquedaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBusquedaMouseExited
        btnBusqueda.setBackground(new Color(125,160,110));
    }//GEN-LAST:event_btnBusquedaMouseExited

    private void btnCancelarReservacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarReservacionMouseEntered
        // TODO add your handling code here:
        btnCancelarReservacion.setBackground(new Color(250,200,85));
    }//GEN-LAST:event_btnCancelarReservacionMouseEntered

    private void btnCancelarReservacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarReservacionMouseExited
        btnCancelarReservacion.setBackground(new Color(250,150,50));
    }//GEN-LAST:event_btnCancelarReservacionMouseExited

    private void btnAjustesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjustesMouseClicked
        // TODO add your handling code here:
        btnEditarPerfil.setVisible(false);
        btnCerrarSesion.setVisible(false);
        
        
    }//GEN-LAST:event_btnAjustesMouseClicked

    private void txtBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaActionPerformed

    private void txtBusquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBusquedaMouseClicked
        // TODO add your handling code here:
        txtBusqueda.setText("");
    }//GEN-LAST:event_txtBusquedaMouseClicked
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btnAjustes;
    private javax.swing.JPanel btnBuscar;
    private javax.swing.JPanel btnBusqueda;
    private javax.swing.JPanel btnCancelarReservacion;
    private javax.swing.JPanel btnCerrarSesion;
    private javax.swing.JPanel btnEditarPerfil;
    private javax.swing.JPanel btnLimpiar;
    private javax.swing.JPanel btnPerfil;
    private javax.swing.JPanel btnPrestamos;
    private javax.swing.JPanel btnSolicitar;
    private javax.swing.JPanel btnTuPerfil;
    private javax.swing.JComboBox<String> cmbFiltro;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCancel;
    private javax.swing.JLabel lblInfB;
    private javax.swing.JLabel lblInfR;
    private javax.swing.JLabel lblSolicitud;
    private javax.swing.JPanel panOptions;
    private javax.swing.JPanel panSearch;
    private javax.swing.JPanel panTable;
    private javax.swing.JTable tblInventario;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables

    private void initTable() {
        tblModel = new DefaultTableModel(header,0){
        @Override
        public boolean isCellEditable(int row, int column){
            return false;
            }
        };
        tblInventario.setModel(tblModel);
        
        
    }
    private void limpiarTabla(){
        for(int i = 0; i < tblInventario.getRowCount(); i++ ){
            tblModel.removeRow(i);
            i --;
        }
    
    }

    private void setHeaderFont(JTableHeader tableHeader, Font font) {
        tableHeader.setFont(font);
        tableHeader.setDefaultRenderer(new DefaultTableCellRenderer() {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            JLabel headerLabel = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            headerLabel.setHorizontalAlignment(JLabel.CENTER);
            return headerLabel;
        }
    });
    }
    
    
}
